apiVersion: v1
kind: Secret
metadata:
  name: {{ include "tms-signalR.fullname" . }}-secrets
type: Opaque
data:
  "RedisParameters:RedisPassword": {{ .Values.secrets."Parameters:RedisPassword" | b64enc | quote }}
  "ConnectionStrings__DefaultConnection":  {{ .Values.secrets.ConnectionStrings__DefaultConnection | b64enc | quote }}