repositories:
  - name: bitnami
    url: https://charts.bitnami.com/bitnami

releases:
  - name: tms-api
    namespace: tms
    chart: ./tms-api
    values:
      - environments/{{ .Environment.Name }}/tms-api-values.yaml
   
  - name: tms-signalR
    namespace: tms
    chart: ./tms-signalR
    values:
      - environments/{{ .Environment.Name }}/tms-signalR-values.yaml

  - name: tms-workerService
    namespace: tms
    chart: ./tms-workerService
    values:
      - environments/{{ .Environment.Name }}/tms-workerService-values.yaml