repositories:
  - name: bitnami
    url: https://charts.bitnami.com/bitnami
  - name: confluentinc
    url: https://confluentinc.github.io/cp-helm-charts/

releases:
  # Infrastructure Dependencies
  - name: redis
    namespace: tms
    chart: bitnami/redis

  - name: kafka
    namespace: tms
    chart: confluentinc/kafka
    values:
      - environments/{{ .Environment.Name }}/kafka-values.yaml


  # Application Services
  - name: tms-api
    namespace: tms
    chart: ./tms-api
    values:
      - environments/{{ .Environment.Name }}/tms-api-values.yaml
   
  - name: tms-signalR
    namespace: tms
    chart: ./tms-signalR
    values:
      - environments/{{ .Environment.Name }}/tms-signalR-values.yaml
    needs:
      - tms/redis

  - name: tms-workerService
    namespace: tms
    chart: ./tms-workerService
    values:
      - environments/{{ .Environment.Name }}/tms-workerService-values.yaml
    needs:
      - tms/kafka