name: Build Docker Images

permissions:
  contents: read

on:
  pull_request:
    paths:
        - "TMS.*/**"
        - "Directory.Build.props"
        - "Directory.Packages.props"
        - "TMS.slnx"
        - "Docker/**"

jobs:
  build:
    name: Docker Build
    runs-on: ubuntu-latest
    timeout-minutes: 10

    strategy:
      matrix:
        include:
          - name: TMS.API
            dockerfile: Docker/Dockerfile.TMS-API
            context: .
          - name: TMS.SignalR
            dockerfile: Docker/Dockerfile.TMS-SignalR
            context: .
          - name: TMS.WorkerService
            dockerfile: Docker/Dockerfile.TMS-WorkerService
            context: .
          - name: TMS.Gateway
            dockerfile: Docker/Dockerfile.TMS-Gateway
            context: .

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v4

      - name: Build image
        uses: docker/build-push-action@v7
        with:
          context: ${{ matrix.context }}
          file: ${{ matrix.dockerfile }}
          push: false